spring.application.name=web_chia_se_tai_lieu_backend

spring.datasource.url=jdbc:mysql://localhost:3306/web_chia_se_tai_lieu
spring.datasource.username=root
spring.datasource.password=
spring.main.banner-mode=off
logging.level.root=warn
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB


app.storage-directory-document=G:\\web_DATN\\storage\\document
app.storage-directory-image=G:\\web_DATN\\storage\\image
app.storage-directory-avatar=G:\\web_DATN\\storage\\avatar
app.storage-directory-video=G:\\web_DATN\\storage\\video
app.storage-directory-subfile=G:\\web_DATN\\storage\\subfile

jwt.secretKey=B8D9F7C728A76F1F0A9CBA8DF8173B25E7934A6F2C84712ED9A1ABCD9F26A7EF
jwt.expirationTime=3600
jwt.refreshTime=36000

libreoffice.path=F:\\LibreOfficee\\LibreOffice\\program\\soffice

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoangvanduc2504@gmail.com
spring.mail.password=rgdmootkleyqnope
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions
spring.ai.openai.chat.options.model= gemini-2.5-flash
spring.ai.retry.max-attempts=3
spring.ai.retry.backoff.initial-interval=30s
spring.ai.retry.backoff.multiplier=2
spring.ai.chat.memory.repository.jdbc.initialize-schema=always




